// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import "strconv"

type Type byte

const (
	Typeunknown        Type = 0
	Typeballoonport    Type = 66
	Typeclosed         Type = 67
	Typeheliport       Type = 72
	Typeseaplane_base  Type = 83
	Typelarge_airport  Type = 108
	Typemedium_airport Type = 109
	Typesmall_airport  Type = 115
)

var EnumNamesType = map[Type]string{
	Typeunknown:        "unknown",
	Typeballoonport:    "balloonport",
	Typeclosed:         "closed",
	Typeheliport:       "heliport",
	Typeseaplane_base:  "seaplane_base",
	Typelarge_airport:  "large_airport",
	Typemedium_airport: "medium_airport",
	Typesmall_airport:  "small_airport",
}

var EnumValuesType = map[string]Type{
	"unknown":        Typeunknown,
	"balloonport":    Typeballoonport,
	"closed":         Typeclosed,
	"heliport":       Typeheliport,
	"seaplane_base":  Typeseaplane_base,
	"large_airport":  Typelarge_airport,
	"medium_airport": Typemedium_airport,
	"small_airport":  Typesmall_airport,
}

func (v Type) String() string {
	if s, ok := EnumNamesType[v]; ok {
		return s
	}
	return "Type(" + strconv.FormatInt(int64(v), 10) + ")"
}
