package gflights
// GENERATED

func init() {
	cities = map[string]string{
		"DAM": "Damascus",
		"SIN": "Singapore",
		"HNL": "Honolulu",
		"CVG": "Cincinnati",
		"KIX": "Osaka",
		"YHZ": "Halifax",
		"SEA": "Seattle",
		"KBP": "Kyiv",
		"YWG": "Winnipeg",
		"HET": "Hohhot",
		"MAO": "Manaus",
		"PKX": "Beijing",
		"ALA": "Almaty",
		"DGO": "Durango",
		"BOJ": "Burgas",
		"CGN": "Cologne",
		"BWN": "Bandar Seri Begawan",
		"BUF": "Buffalo",
		"MDW": "Chicago",
		"COK": "Kochi",
		"MEM": "Memphis",
		"BGY": "Milan",
		"SNA": "Santa Ana",
		"VNO": "Vilnius",
		"AMM": "Amman",
		"PRG": "Prague",
		"TUN": "Tunisia",
		"GUM": "Guam",
		"EZE": "Buenos Aires",
		"ITM": "Osaka",
		"LJU": "Ljubljana",
		"TYN": "Taiyuan",
		"ADL": "Adelaide",
		"CTA": "Catania",
		"AUA": "Aruba",
		"FDF": "Fort-de-France",
		"DFW": "Dallas",
		"DRW": "Darwin",
		"LEJ": "Leipzig",
		"MZT": "Mazatlan",
		"CNX": "Chiang Mai",
		"SYD": "Sydney",
		"FCO": "Rome",
		"CJU": "Jeju-si",
		"GOX": "Genoa",
		"RIC": "Richmond",
		"FUK": "Fukuoka",
		"PBI": "West Palm Beach",
		"DAC": "Dhaka",
		"OKC": "Oklahoma City",
		"SAT": "San Antonio",
		"HKG": "Hong Kong",
		"BTS": "Bratislava",
		"TPE": "Taipei City",
		"KWI": "Kuwait City",
		"FOC": "Fuzhou",
		"DHX": "Kediri",
		"BOG": "Bogotá",
		"DMM": "Dammam",
		"JAX": "Jacksonville",
		"EBB": "Entebbe",
		"SSH": "Sharm El-Sheikh",
		"KOJ": "Kagoshima",
		"YUL": "Montreal",
		"DXB": "Dubai",
		"NNG": "Nanning",
		"MAA": "Chennai",
		"ANC": "Anchorage",
		"CPH": "Copenhagen",
		"CZM": "Cozumel",
		"FRA": "Frankfurt",
		"BON": "Bonaire",
		"TLV": "Tel Aviv-Yafo",
		"CNF": "Belo Horizonte",
		"GDN": "Gdańsk",
		"JED": "Jeddah",
		"ZRH": "Zürich",
		"KHI": "Karachi",
		"VKO": "Moscow",
		"CAG": "Cagliari",
		"TRV": "Thiruvananthapuram",
		"TFU": "Chengdu",
		"VRN": "Verona",
		"CDG": "Paris",
		"THR": "Tehran",
		"LHW": "Lanzhou",
		"PPT": "Tahiti",
		"WUH": "Wuhan",
		"CMB": "Colombo",
		"GMP": "Seoul",
		"CEB": "Cebu City",
		"HRG": "Hurghada",
		"BOD": "Bordeaux",
		"SKP": "Skopje",
		"MID": "Merida",
		"LTN": "London",
		"ETM": "Eilat",
		"RNO": "Reno",
		"TOS": "Tromsø Municipality",
		"GIG": "Rio de Janeiro",
		"BEG": "Belgrade",
		"PBM": "Paramaribo",
		"ATL": "Atlanta",
		"YNT": "Yantai",
		"YYT": "St. John's",
		"BGO": "Bergen",
		"SFO": "San Francisco",
		"GBE": "Gaborone",
		"SVG": "Stavanger",
		"HYD": "Hyderabad",
		"CUZ": "Historic Sanctuary of Machu Picchu",
		"YOW": "Ottawa",
		"GOI": "Genoa",
		"IBZ": "Ibiza",
		"ARN": "Stockholm",
		"IAH": "Houston",
		"SJC": "San Jose",
		"LED": "Saint Petersburg",
		"BLQ": "Bologna",
		"SSA": "El Salvador",
		"ICN": "Seoul",
		"AEP": "Buenos Aires",
		"DJJ": "Jayapura",
		"ENO": "Encarnación de Díaz",
		"LGA": "New York",
		"IST": "İstanbul",
		"SCL": "Santiago",
		"SHJ": "Sharjah",
		"ORD": "Chicago",
		"NBO": "Nairobi",
		"BCN": "Barcelona",
		"IKA": "Tehran",
		"VIE": "Vienna",
		"LCA": "Larnaca",
		"SDF": "Louisville",
		"VVO": "Vladivostok",
		"MEX": "Mexico City",
		"HAK": "Haikou",
		"HEL": "Helsinki",
		"UBN": "Ulaanbaatar",
		"OMA": "Omaha",
		"NCE": "Nice",
		"KJA": "Krasnoyarsk",
		"GYE": "Guayaquil",
		"TAO": "Qingdao",
		"CKG": "Chongqing",
		"ABQ": "Albuquerque",
		"OGG": "Kahului",
		"SID": "San Salvador",
		"SVX": "Yekaterinburg",
		"AYT": "Antalya",
		"NLU": "Mexico City",
		"DUR": "Durban",
		"SJU": "San Juan",
		"SJD": "San José del Cabo",
		"DUB": "Dublin",
		"MRS": "Marseille",
		"ZIA": "Zhukovskiy",
		"BLR": "Bengaluru",
		"FNC": "Madeira",
		"BOM": "Mumbai",
		"LUN": "Lusaka",
		"FUE": "Fuerteventura",
		"TPA": "Tampa",
		"KRK": "Kraków",
		"MBA": "Mombasa",
		"PLS": "Providenciales",
		"LIM": "Lima",
		"LHR": "London",
		"KWL": "Guilin",
		"HAJ": "Hanover",
		"SUB": "Surabaya",
		"PDX": "Portland",
		"AMS": "Amsterdam",
		"FLN": "Florianópolis",
		"KUF": "Samara",
		"UVF": "Saint Lucia",
		"HRE": "Harare",
		"DOH": "Doha",
		"PVG": "Shanghai",
		"CLE": "Cleveland",
		"BEL": "Belém",
		"DLM": "Dalaman",
		"MLA": "Malta",
		"LAD": "Luanda",
		"AKL": "Auckland",
		"MUC": "Munich",
		"CAN": "Guangzhou",
		"PHX": "Phoenix",
		"KUL": "Federal Territory of Kuala Lumpur",
		"BLA": "Barcelona",
		"PWM": "Portland",
		"KEF": "Reykjavík",
		"RDU": "Raleigh",
		"VIX": "Vitoria-Gasteiz",
		"MXP": "Milan",
		"MFM": "Macao",
		"CSX": "Changsha",
		"TSN": "Tianjin",
		"XIY": "Xi'An",
		"EWR": "Newark",
		"SXM": "Saint Martin",
		"DWC": "Dubai",
		"YYZ": "Toronto",
		"RUH": "Riyadh",
		"DQM": "Duqm",
		"ADB": "İzmir",
		"YEG": "Edmonton",
		"GUA": "Guatemala City",
		"BJV": "Bodrum",
		"KMG": "Kunming",
		"SMF": "Sacramento",
		"NAP": "Naples",
		"HAN": "Hanoi",
		"KHN": "Nanchang",
		"MVD": "Montevideo",
		"DPS": "Denpasar",
		"SRQ": "Sarasota",
		"NUE": "Nuremberg",
		"UIO": "Quito",
		"PUJ": "Punta Cana",
		"EIN": "Eindhoven",
		"RGN": "Yangon",
		"KNO": "Medan",
		"GVA": "Geneva",
		"PAP": "Port-au-Prince",
		"TLS": "Toulouse",
		"LAX": "Los Angeles",
		"NRT": "Tokyo",
		"BNE": "Brisbane",
		"CGO": "Zhengzhou",
		"BPS": "Porto Seguro",
		"HRB": "Harbin",
		"OTP": "Bucharest",
		"GCM": "Grand Cayman",
		"BER": "Berlin",
		"URC": "Ürümqi",
		"ESB": "Ankara",
		"HAM": "Hamburg",
		"EVN": "Yerevan",
		"BZE": "Belize City",
		"ROB": "Monrovia",
		"RUN": "Saint-Denis",
		"CCS": "Caracas",
		"MCT": "Muscat",
		"TIJ": "Tijuana",
		"BAH": "Bahrain",
		"OPO": "Porto",
		"CMN": "Casablanca",
		"UPG": "Makassar",
		"ZNZ": "Zanzibar Archipelago",
		"NGB": "Ningbo",
		"MTY": "Monterrey",
		"SKG": "Thessaloniki",
		"MKE": "Milwaukee",
		"TIA": "Tirana",
		"PSA": "Pisa",
		"GOT": "Gothenburg",
		"MDL": "Mandalay",
		"BWI": "Baltimore",
		"WNZ": "Wenzhou",
		"LIR": "Liberia",
		"PIT": "Pittsburgh",
		"WLG": "Wellington",
		"TRD": "Trondheim",
		"WDH": "Windhoek",
		"BOS": "Boston",
		"BGW": "Baghdad",
		"ABV": "Abuja",
		"PEK": "Beijing",
		"SAL": "San Salvador",
		"COV": "Mersin",
		"KTM": "Kathmandu",
		"SYX": "Sanya",
		"TAS": "Tashkent",
		"SZX": "Shenzhen",
		"SHO": "Manzini",
		"HAV": "Havana",
		"SHE": "Shenyang",
		"GRU": "São Paulo",
		"CCU": "Kolkata",
		"LAS": "Las Vegas",
		"SAV": "Savannah",
		"BLL": "Billund",
		"WAW": "Warsaw",
		"SDQ": "Santo Domingo",
		"ADD": "Addis Ababa",
		"STR": "Stuttgart",
		"ASB": "Ashgabat",
		"PTP": "Pointe-à-Pitre",
		"FLL": "Fort Lauderdale",
		"MNL": "Manila",
		"MPM": "Maputo",
		"CUR": "Curaçao",
		"SYZ": "Shiraz",
		"TNA": "Jinan",
		"DEN": "Denver",
		"CTS": "Sapporo",
		"PER": "Perth",
		"NGO": "Nagoya",
		"ACE": "Lanzarote",
		"AGT": "Ciudad del Este",
		"NKG": "Nanjing",
		"OAK": "Oakland",
		"EHU": "Ezhou",
		"SAI": "Krong Siem Reap",
		"MCI": "Kansas City",
		"LRM": "La Romana",
		"MCO": "Orlando",
		"CAY": "Cayenne",
		"KHH": "Kaohsiung City",
		"NAS": "Nassau",
		"DAR": "Dar es Salaam",
		"CMH": "Columbus",
		"ISB": "Islamabad",
		"MWX": "Muan-gun",
		"VAR": "Varna",
		"AGP": "Málaga",
		"AUH": "Abu Dhabi",
		"AUS": "Austin",
		"HND": "Tokyo",
		"ALC": "Alicante",
		"STL": "St. Louis",
		"DCA": "Washington",
		"DME": "Moscow",
		"DTW": "Detroit",
		"LUX": "Luxembourg",
		"TFS": "Tenerife",
		"SAW": "İstanbul",
		"LYS": "Lyon",
		"MAN": "Manchester",
		"EDI": "Edinburgh",
		"TLL": "Tallinn",
		"TRN": "Turin",
		"POM": "Port Moresby",
		"KGL": "Kigali",
		"BUD": "Budapest",
		"CUN": "Cancún",
		"MSP": "Minneapolis",
		"BHX": "Birmingham",
		"YQB": "Québec City",
		"CLT": "Charlotte",
		"YYC": "Calgary",
		"SGN": "Ho Chi Minh City",
		"OVB": "Novosibirsk",
		"JIB": "Djibouti",
		"JNB": "Johannesburg",
		"PVR": "Puerto Vallarta",
		"SOF": "Sofia",
		"MJI": "Tripoli",
		"VRA": "Varadero",
		"PNH": "Phnom Penh",
		"DMK": "Bangkok",
		"BRI": "Bari",
		"OKA": "Okinawa",
		"LOS": "Lagos",
		"SLC": "Salt Lake City",
		"CGQ": "Changchun",
		"MLE": "Malé",
		"NKC": "Nouakchott",
		"DLC": "Dalian",
		"HIR": "Honiara",
		"HGH": "Hangzhou",
		"BRU": "Brussels",
		"XMN": "Xiamen",
		"CHC": "Christchurch",
		"GDL": "Guadalajara",
		"STN": "London",
		"FOR": "Fortaleza",
		"MED": "Madinah",
		"KWE": "Guiyang",
		"MEL": "Melbourne",
		"MSQ": "Minsk",
		"CAI": "Cairo",
		"ONT": "Toronto",
		"IAD": "Washington",
		"KIN": "Kingston",
		"IND": "Indianapolis",
		"NDJ": "N'Djamena",
		"AER": "Sochi",
		"PMI": "Palma",
		"MHD": "Mashhad",
		"MSY": "New Orleans",
		"RIX": "Riga",
		"HKT": "Phuket",
		"TNR": "Antananarivo",
		"FIH": "Kinshasa",
		"JUB": "Juba",
		"CPT": "Cape Town",
		"BKO": "Bamako",
		"FAO": "Faro District",
		"NIM": "Niamey",
		"DSS": "Dakar",
		"ACC": "Accra",
		"PUS": "Busan",
		"ALG": "Algiers [El Djazaïr]",
		"SDJ": "Sendai",
		"GLA": "Glasgow",
		"HSR": "Rajkot",
		"BPN": "Balikpapan",
		"DUS": "Düsseldorf",
		"DVO": "Davao City",
		"LPA": "Municipality of Las Palmas",
		"SFB": "Orlando",
		"SAN": "San Diego",
		"PTY": "Panama City",
		"TUL": "Tulsa",
		"PHL": "Philadelphia",
		"JFK": "New York",
		"BDS": "Brindisi",
		"SNN": "Shannon",
		"LGW": "London",
		"BEY": "Beirut",
		"BJL": "Banjul",
		"ORY": "Paris",
		"SYR": "Syracuse",
		"FRU": "Bishkek",
		"SHA": "Shanghai",
		"BNA": "Nashville",
		"FNA": "Freetown",
		"NQZ": "Astana",
		"HER": "Heraklion",
		"SEZ": "Mahé",
		"DEL": "New Delhi",
		"MAD": "Madrid",
		"ASU": "Asunción",
		"OSL": "Oslo",
		"TGD": "Podgorica",
		"MRU": "Mascarene Islands",
		"SVO": "Moscow",
		"PDL": "Ponta Delgada",
		"SCQ": "Santiago de Compostela",
		"CTU": "Chengdu",
		"GSV": "Saratov",
		"PMO": "Palermo",
		"TBS": "Tbilisi",
		"BDL": "Hartford",
		"KZN": "Kazan",
		"BSL": "Basel",
		"MIA": "Miami",
		"VCE": "Venice",
		"ORF": "Norfolk",
		"PVD": "Providence",
		"LIS": "Lisbon",
		"BSB": "Brasília",
		"RSW": "Fort Myers",
		"CGK": "Jakarta",
		"BFS": "Belfast",
		"VVI": "Santa Cruz de la Sierra",
		"ATH": "Athens",
		"GYD": "Baku",
		"YVR": "Vancouver",
		"BKK": "Bangkok",
		"LHE": "Lahore",
		"VLI": "Port Vila",
		"ZAG": "Zagreb",
}
}
